# Fuzzy Enhanced Russell Graph Efficiency Measure (FERM)

\begin{eqnarray}\label{prob: FERM}
\mbox{(FERM)}\ \ {R}^F(\tilde{X}_p, \tilde{Y}_p)= 
&\mbox{Min} & {\displaystyle\frac{\displaystyle\frac{1}{M}\sum_{i=1}^{M}\theta_i}{\displaystyle\frac{1}{S}\sum_{r=1}^{S}\gamma_r    }    }
\\[0.5em]
&\mbox{s.t.} & {\displaystyle\sum_{j=1}^{N}} \lambda_j \tilde{x}_{ij} \preceq \theta_i \tilde{x}_{ip} ,\quad i=1,\dots, M
\nonumber\\[0.5em]
&& {\displaystyle\sum_{j=1}^{n}} \lambda_j \tilde{y}_{rj} \succeq \gamma_r \tilde{y}_{rp} ,\quad r=1,\dots, S,
\nonumber\\[0.5em]
&& \theta_i\le 1, \gamma_r\ge 1,\quad \forall i,r, \nonumber\\
&& \lambda_j \geq 0 ,\quad j=1,\dots, N, \nonumber
\end{eqnarray}

where the different inputs $\tilde{x}_{ij}$ and outputs $\tilde{y}_{rj}$ belong to $(RPFN_k)_+$, i.e. 


\begin{eqnarray*}
\tilde{x}_{ij} &=& ({x}^{-}_{{ij0}},{x}^{-}_{{ij1}},\dots ,{x}^{-}_{{ijk}},{x}^{+}_{{ijk}},\dots, {x}^{+}_{{ij1}},{x}^{+}_{{ij0}}),  \quad i=1,\dots, M, \ \ j=1,\dots, N\\
\tilde{y}_{rj} &=& ({y}^{-}_{{rj0}},{y}^{-}_{{rj1}},\dots ,{y}^{-}_{{rjk}},{y}^{+}_{{rjk}},\dots, {y}^{+}_{{rj1}},{y}^{+}_{{rj0}}),  \quad r=1,\dots, S, \ \ j=1,\dots, N 
\end{eqnarray*}




## Example: Hsiao et al 2011


In [1]:
K = 1 # K=1-polygonal fuzzy number, RPFN_k
L = 2*(K+1) # 2(k+1), 
N = 5 # DMUs
M = 2 # inputs X
S = 1 # outputs Y

# DATA: Hsiao et al (2011)
INPUTS <- array(c(12,12,12,12, 8,8,8,8, 
                 14,14,14,14, 7,7,7,7, 
                 20,20,20,20, 8,8,8,8,
                 20,20,20,20, 6,6,6,6,
                 20,20,20,20, 5,6,6,7), c(L,M,N)) 
#
OUTPUTS <- array(c(10,10,10,10, 
                   10,10,10,10, 
                   10,10,10,10, 
                   10,10,10,10, 
                   10,10,10,10),c(L,S,N)) 

# Understand the structure:
# First fuzzy element for each input of each DMU:
INPUTS[1,,]
# First DMU:
INPUTS[,,1]
# Second input for each DMU:
INPUTS[,2,]

[,1] [,2] [,3] [,4] [,5]
[1,] 12   14   20   20   20  
[2,]  8    7    8    6    5

[,1] [,2]
[1,] 12   8   
[2,] 12   8   
[3,] 12   8   
[4,] 12   8

[,1] [,2] [,3] [,4] [,5]
[1,] 8    7    8    6    5   
[2,] 8    7    8    6    6   
[3,] 8    7    8    6    6   
[4,] 8    7    8    6    7

**Notes:**
<font color='blue'>For computational purposes, and to simplify notation, let use the equivalent one:</font>

\begin{eqnarray*}
\tilde{x}_{ij} &=& ({x}_{{ij1}},{x}_{{ij2}},\dots ,{x}_{{ijL}}),  \quad i=1,\dots, M, \ \ j=1,\dots, N, \ \ L= 2(K+1)\\
\tilde{y}_{rj} &=& ({y}_{{rj1}},{y}_{{rj2}},\dots ,{y}_{{rjL}}),  \quad r=1,\dots, S, \ \ j=1,\dots, N 
\end{eqnarray*}

Therefore, the correspondence is:

$\color{blue}{\tilde{a} = ({a}^{-}_{{0}},{a}^{-}_{{1}},\dots ,{a}^{-}_{{k}},{a}^{+}_{{k}},\dots, {a}^{+}_{{1}},{a}^{+}_{{0}}) \equiv  (a_1,a_2,\ldots,a_L)}$


where the number of components is $\color{blue}{L=2(K+1)}$, corresponding to the two elements for eack $k+1$ levels of $(RPFN_k)$ fuzzy number. 

\begin{eqnarray*}
({a}^{-}_{{0}},{a}^{+}_{{0}}) &\equiv& (a_1,a_L) \\
({a}^{-}_{{1}},{a}^{+}_{{1}}) &\equiv& (a_2,a_{L-1}) \\
\vdots && \\
({a}^{-}_{{l}},{a}^{+}_{{l}}) &\equiv& (a_{l},a_{L-l}) \quad l=0,1,\ldots,k\\
\vdots && \\
({a}^{-}_{{K}},{a}^{+}_{{K}}) &\equiv& (a_{L/2},a_{L/2+1}) 
\end{eqnarray*}

# Modified & linear FERM:

To get a linear problem we define the new variables, 

\begin{equation}\label{eq: new variables}
\begin{array}{c}
    {\displaystyle\frac{1}{\beta}}={\displaystyle{\frac{1}{2S(K+1)}\sum_{r=1}^{S} \sum_{l=0}^{K} (\gamma_{rk}^{L}+\gamma_{rk}^{R})}},\quad \lambda'_j=\beta\lambda_j,\\
    \theta_{ik}^{'L}=\beta\theta_{ik}^{L},\quad
    \theta_{ik}^{'R}=\beta\theta_{ik}^{R},\quad\gamma_{rk}^{'L}=\beta\gamma_{rk}^{L},\quad\gamma_{rk}^{'R}=\beta\gamma_{rk}^{R},\quad\forall j,i,r,k. 
    %j=1,\dots,n,\; i=1,\dots,m,\; r=1,\dots, s.
    \end{array}
\end{equation}


Reformulating (MFERM}) using the new variables, we have:

\begin{eqnarray}\label{prob: PLFERM}
\mbox{(LMFERM)}\ \ {R}^F_M(\tilde{X}_p, \tilde{Y}_p)= &\mbox{Min} & 
\displaystyle \frac{1}{2M(K+1)}\sum_{i=1}^{M} \sum_{k=0}^{K} (\theta_{ik}^{'L}+\theta_{ik}^{'R}) 
\color{blue}{= \frac{1}{ML}\sum_{i=1}^{M} \sum_{l=1}^{L} \theta_{il}}
\\[0.5em]
&\mbox{s.t.} & \displaystyle\frac{1}{2S(K+1)}\sum_{r=1}^{S}  \sum_{k=0}^{K} (\gamma_{rk}^{'L}+\gamma_{rk}^{'R} )
= 1 \color{blue}{= \frac{1}{SL}\sum_{r=1}^{S} \sum_{l=1}^{L} \gamma_{rl}}
\nonumber\\
&& \left. \begin{array}{r}
{\displaystyle\sum_{j=1}^{N}} \lambda'_j {x}^{-}_{{ijk}} \leq 
\theta_{ik}^{'L} {x}^{-}_{ipk} ,\quad i=1,\dots, M, \ \ k=0,\ldots,K
\nonumber\\[0.5em]
{\displaystyle\sum_{j=1}^{N}} \lambda'_j {x}^{+}_{{ijk}} \leq 
\theta_{ik}^{'R} {x}^{+}_{ipk} ,\quad i=1,\dots, M, \ \ k=0,\ldots,K
\end{array} \right\} 
\color{blue}{ \sum_{j=1}^{N}   \lambda'_j {x}_{{ijl}}  \leq 
\theta_{il} {x}_{ipl} ,\quad i=1,\dots, M, \ \ l=1,\ldots,L }
\nonumber\\[0.5em]
&& \left. \begin{array}{r}
{\displaystyle\sum_{j=1}^{N}} \lambda'_j {y}^{-}_{rjk} \geq 
\gamma_{rk}^{'L} {y}^{-}_{rpk} ,\quad r=1,\dots, S, \ \ k=0,\ldots,K
\nonumber\\[0.5em]
 {\displaystyle\sum_{j=1}^{N}} \lambda'_j {y}^{+}_{rjl} \geq 
\gamma_{rk}^{'R} {y}^{+}_{rpk} ,\quad r=1,\dots, S, \ \ k=1,\ldots,K 
\end{array} \right\} 
\color{blue}{{\displaystyle\sum_{j=1}^{N}} \lambda'_j {y}_{rjl} \geq 
\gamma_{rl} {y}_{rpl} ,\quad r=1,\dots, S, \ \ l=1,\ldots,L }
\nonumber\\[0.5em]
&& \theta_{ik}^{'L} \le \beta, \quad  \theta_{ik}^{'R} \le \beta,
\quad i=1,\dots, M,\; k=0,\ldots,K  \quad
\color{blue}{\equiv  \theta_{il} \le \beta \quad i=1,\dots, M,\; l=1,\ldots,L }
\nonumber\\
&& \gamma_{rk}^{'L} \ge \beta, \quad \gamma_{rk}^{'R} \ge \beta,
\quad r=1,\dots, S,\;k=0,\ldots,K \quad
\color{blue}{\equiv  \gamma_{rl} \ge \beta \quad r=1,\dots, S,\; l=1,\ldots,L }
\nonumber\\
&& \beta>0,\\
&& \lambda'_j \geq 0 ,\quad j=1,\dots, N \nonumber
\end{eqnarray}

**NOTE:** To solve the above problem with lp (lpSolve package), we need to transform it in matrix notation:  

\begin{eqnarray*}
\ \ &\mbox{Min } & Cx  \\
&s.t.& Ax \leq b,  \\
&& x\geq 0
\end{eqnarray*}

where, $x = (\lambda_1,\ldots,\lambda_N,\theta_{11},\ldots,\theta_{1L},\ldots,\theta_{M1},\ldots,\theta_{ML},
\gamma_{11},\ldots,\gamma_{1L},\ldots,\gamma_{S1},\ldots,\gamma_{SL},\beta)$

There are $N+(M+S)L+1$ variables, and $1+ML+SL+ML+SL+1 = 2L(M+S)+2$ constraints.

In [2]:
# Define variable arrays, for each DMU (N):
ERM = array(0,N)
beta = array(0,N)
lambda = array(0,c(N,N))
theta = array(0,c(N,M*L))
gamma = array(0,c(N,S*L))

Targets.X = array(0,c(L,M,N))
Targets.Y = array(0,c(L,S,N))


In [3]:
beta
gamma

[1] 0 0 0 0 0

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0   
[4,] 0    0    0    0   
[5,] 0    0    0    0

## Example: Hsiao et al 2011 (continuation)

LMFERM for this example is, for DMU $p=5$

\begin{eqnarray}
(LMFERM)\ \ {R}^F_M(\tilde{X}_1, \tilde{Y}_1)= & {Min} & \ \ 
\frac{1}{2\cdot 4}\sum_{i=1}^{2} \sum_{l=1}^{4} \theta'_{il} 
\ \   = \ \  
\theta'_{11} +  \theta'_{12} +  \theta'_{13} +  \theta'_{14} + 
\theta'_{21} +  \theta'_{22} +  \theta'_{23} +  \theta'_{24} 
\\[0.5em]
&\mbox{s.t.} & \displaystyle\frac{1}{1\cdot4}\sum_{r=1}^{1} \sum_{l=1}^{4} \gamma'_{rl} 
\ \ = \ \ \frac{1}{4}\left( \gamma'_{11} + \gamma'_{12} + \gamma'_{13} + \gamma'_{14} \right) = 1
\nonumber\\
&&  \left. \begin{array}{lcr}
12\lambda'_1 + 14\lambda'_2 + 20\lambda'_3 + 20\lambda'_4 + 20\lambda'_5 &\leq& 20\theta'_{11} \\
12\lambda'_1 + 14\lambda'_2 + 20\lambda'_3 + 20\lambda'_4 + 20\lambda'_5 &\leq& 20\theta'_{12} \\
12\lambda'_1 + 14\lambda'_2 + 20\lambda'_3 + 20\lambda'_4 + 20\lambda'_5 &\leq& 20\theta'_{13} \\
12\lambda'_1 + 14\lambda'_2 + 20\lambda'_3 + 20\lambda'_4 + 20\lambda'_5 &\leq& 20\theta'_{14}
\end{array} \right\} \ \ i=1
\nonumber\\[0.5em]
&&  \left. \begin{array}{lcr}
8\lambda'_1 + 7\lambda'_2 + 8\lambda'_3 + 6\lambda'_4 + 5\lambda'_5 &\leq& 5\theta'_{21} \\
8\lambda'_1 + 7\lambda'_2 + 8\lambda'_3 + 6\lambda'_4 + 6\lambda'_5 &\leq& 6\theta'_{22} \\
8\lambda'_1 + 7\lambda'_2 + 8\lambda'_3 + 6\lambda'_4 + 6\lambda'_5 &\leq& 6\theta'_{23} \\
8\lambda'_1 + 7\lambda'_2 + 8\lambda'_3 + 6\lambda'_4 + 7\lambda'_5 &\leq& 7\theta'_{24}
\end{array} \right\} \ \ i=2
\nonumber\\[0.5em]
&& \left. \begin{array}{lcr}
10\lambda'_1 + 10\lambda'_2 + 10\lambda'_3 + 10\lambda'_4 + 10\lambda'_5 &\geq& 10\gamma'_{11}\\  
10\lambda'_1 + 10\lambda'_2 + 10\lambda'_3 + 10\lambda'_4 + 10\lambda'_5 &\geq& 10\gamma'_{12}\\  
10\lambda'_1 + 10\lambda'_2 + 10\lambda'_3 + 10\lambda'_4 + 10\lambda'_5 &\geq& 10\gamma'_{13}\\  
10\lambda'_1 + 10\lambda'_2 + 10\lambda'_3 + 10\lambda'_4 + 10\lambda'_5 &\geq& 10\gamma'_{14}\\  
\end{array} \right\} \ \ r=1
\nonumber\\[0.5em]
&& \theta'_{il} \le \beta \quad i=1,2,\; l=1,\ldots,4
\nonumber\\
&& \gamma'_{rl} \ge \beta \quad r=1 \; l=1,\ldots,4 
\nonumber\\
&& \beta>0, \\
&& \lambda'_j \geq 0 ,\quad j=1,\dots, 5 \nonumber
\end{eqnarray}



In [4]:
# There are 
NV = N+(M+S)*L+1 # variables, and
NC = 2*L*(M+S)+2 # constraints

NV; NC

[1] 18

[1] 26

To solve the above problem with lp (lpSolve package), we need to transform it in matrix notation:  

\begin{eqnarray*}
\ \ &\mbox{Min } & Cx \\
&s.t.& Ax \leq b,  \\
&& x\geq 0, \ \ x \in \mathbb{R}^{18}
\end{eqnarray*}

where, 

$x = \begin{pmatrix}
  \lambda_1 & \lambda_2 & \lambda_3 & \lambda_4 & \lambda_5 &
  \theta_{11} &  \theta_{12} &  \theta_{13} &  \theta_{14} & 
   \theta_{21} &  \theta_{22} &  \theta_{23} &  \theta_{24} &
   \gamma_{11} &  \gamma_{12} &  \gamma_{13} &  \gamma_{14}& \beta
\end{pmatrix}
$

$A = \left(\begin{array}{ccccc | cccccccc | cccc | c}
  \lambda_1 & \lambda_2 & \lambda_3 & \lambda_4 & \lambda_5 &
  \theta_{11} &  \theta_{12} &  \theta_{13} &  \theta_{14} & 
   \theta_{21} &  \theta_{22} &  \theta_{23} &  \theta_{24} &
   \gamma_{11} &  \gamma_{12} &  \gamma_{13} &  \gamma_{14}& \beta\\
   0 &0 & 0&0 & 0&0 &0 & 0& 0& 0& 0& 0& 0&  \frac{1}{4}&  \frac{1}{4}& \frac{1}{4}& \frac{1}{4} & 0\\
   \hline
   12& 14& 20& 20& 20& -20& 0& 0& 0&0 &0 & 0& 0& 0& 0& 0& 0&0 \\
   12& 14& 20& 20& 20& 0& -20& 0& 0&0 &0 & 0& 0& 0& 0& 0& 0&0 \\
   12& 14& 20& 20& 20& 0& 0& -20& 0&0 &0 & 0& 0& 0& 0& 0& 0&0 \\
   12& 14& 20& 20& 20& 0& 0& 0& -20& 0 &0 & 0& 0& 0& 0& 0& 0&0 \\
   8& 7& 8& 6& 5& 0& 0& 0& 0& -5 &0 & 0& 0& 0& 0& 0& 0&0 \\
   8& 7& 8& 6& 6& 0& 0& 0& 0& 0 &-6 & 0& 0& 0& 0& 0& 0&0 \\
   8& 7& 8& 6& 6& 0& 0& 0& 0& 0 &0 & -6& 0& 0& 0& 0& 0&0 \\
   8& 7& 8& 6& 7& 0& 0& 0& 0& 0 &0 & 0& -7& 0& 0& 0& 0&0 \\
   \hline
   10&10 & 10&10 &10 & 0&0 &0 &0 & 0&0 &0 &0 & -10& 0& 0&0 &0 \\
   10&10 & 10&10 &10 & 0&0 &0 &0 & 0&0 &0 &0 & 0& -10& 0&0 &0 \\
   10&10 & 10&10 &10 & 0&0 &0 &0 & 0&0 &0 &0 & 0& 0& -10&0 &0 \\
   10&10 & 10&10 &10 & 0&0 &0 &0 & 0&0 &0 &0 & 0& 0& 0&-10 &0 \\
   \hline
   0&0 &0 &0 &0 & 1&0 &0 &0 & 0&0 & 0& 0& 0& 0&0 & 0& -1 \\
   0&0 &0 &0 &0 & 0&1 &0 &0 & 0&0 & 0& 0& 0& 0&0 & 0& -1 \\
   0&0 &0 &0 &0 & 0&0 &1 &0 & 0&0 & 0& 0& 0& 0&0 & 0& -1 \\
   0&0 &0 &0 &0 & 0&0 &0 &1 & 0&0 & 0& 0& 0& 0&0 & 0& -1 \\
   0&0 &0 &0 &0 & 0&0 &0 &0 & 1&0 & 0& 0& 0& 0&0 & 0& -1 \\
   0&0 &0 &0 &0 & 0&0 &0 &0 & 0&1 & 0& 0& 0& 0&0 & 0& -1 \\
   0&0 &0 &0 &0 & 0&0 &0 &0 & 0&0 & 1& 0& 0& 0&0 & 0& -1 \\
   0&0 &0 &0 &0 & 0&0 &0 &0 & 0&0 & 0& 1& 0& 0&0 & 0& -1 \\
   \hline
   0&0 &0 &0 &0 & 0&0 &0 &0 & 0&0 & 0& 0& 1& 0&0 & 0& -1 \\
   0&0 &0 &0 &0 & 0&0 &0 &0 & 0&0 & 0& 0& 0& 1&0 & 0& -1 \\
   0&0 &0 &0 &0 & 0&0 &0 &0 & 0&0 & 0& 0& 0& 0&1 & 0& -1 \\
   0&0 &0 &0 &0 & 0&0 &0 &0 & 0&0 & 0& 0& 0& 0&0 & 1& -1 \\
   \hline
  0&0 &0 &0 &0 & 0&0 &0 &0 & 0&0 & 0& 0& 0& 0&0 & 0& 1 
 \end{array} \right)
 \begin{matrix}
  \\ = \\ \leq \\ \leq \\ \leq \\ \leq \\ \leq \\ \leq \\ \leq \\ \leq \\
 \geq \\ \geq \\ \geq \\ \geq \\ 
 \leq \\ \leq \\ \leq \\ \leq \\ \leq \\ \leq \\ \leq \\ \leq \\
 \geq \\ \geq \\ \geq \\ \geq \\ >
 \end{matrix}
 \quad 
 b = \begin{pmatrix}
1 \\ 0 \\ 0 \\ 0 \\ 0 \\ 0 \\ 0 \\ 0 \\ 0 \\ 0 \\
 0 \\ 0 \\ 0 \\ 0 \\ 
 0 \\ 0 \\ 0 \\ 0 \\ 0\\ 0 \\ 0\\ 0 \\
 0 \\ 0 \\ 0 \\ 0 \\ 0
\end{pmatrix}
$

and 

$
C = \begin{pmatrix}
  0 & 0 & 0 & 0 & 0 &
  \frac{1}{8} &  \frac{1}{8} & \frac{1}{8} & \frac{1}{8} & 
   \frac{1}{8} &  \frac{1}{8} & \frac{1}{8} &  \frac{1}{8} &
   0 &  0 &  0 &  0& 0
\end{pmatrix}
$




In [5]:
dmu = 5

## Set the coefficients of the decision variables -> C
C <- c(rep(0,N),rep(1/(M*L),M*L),rep(0,S*L+1))

C

length(C)

[1] 0.000 0.000 0.000 0.000 0.000 0.125 0.125 0.125 0.125 0.125 0.125 0.125
[13] 0.125 0.000 0.000 0.000 0.000 0.000

[1] 18

In [6]:
# Right hand side for the constraints
B <- c(1,rep(0,NC-1))

B

length(B)

[1] 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[1] 26

In [7]:
# Direction of the constraints
constraints_direction  <- c("=",rep("<=",M*L), rep(">=",S*L), 
                               rep("<=",M*L), rep(">=",S*L),">") 

constraints_direction

length(constraints_direction)

[1] "="  "<=" "<=" "<=" "<=" "<=" "<=" "<=" "<=" ">=" ">=" ">=" ">=" "<=" "<="
[16] "<=" "<=" "<=" "<=" "<=" "<=" ">=" ">=" ">=" ">=" ">"

[1] 26

Column indexes: 

$\lambda_j, \ \ j=1,\ldots,N \quad : A[,j]$ 

$\theta{il}, \ \ i=1,\ldots,M, \ \ l=1,\ldots,L \quad : A[,N+L*(i-1)+l]$ 

$\gamma{rl}, \ \ r=1,\ldots,S, \ \ l=1,\ldots,L \quad : A[,N+L*M+L*(r-1)+l]$ 

$\beta : \ \ A[,N+L*M+L*S+1]$ 


Constraints indexes:

$\frac{1}{SL}\sum_{r=1}^{S} \sum_{l=1}^{L} \gamma_{rl} = 1 \quad \Rightarrow \quad A[1,]$

$\sum_{j=1}^{N}   \lambda'_j {x}_{{ijl}}  \leq 
\theta_{il} {x}_{ipl} ,\quad i=1,\dots, M, \ \ l=1,\ldots,L \quad \Rightarrow \quad A[1+L*(i-1)+l,] $

$\displaystyle\sum_{j=1}^{N} \lambda'_j {y}_{rjl} \geq 
\gamma_{rl} {y}_{rpl} ,\quad r=1,\dots, S, \ \ l=1,\ldots,L \quad \Rightarrow \quad A[1+L*M+L*(r-1)+l,] $

$\theta_{il} \le \beta \quad i=1,\dots, M,\; l=1,\ldots,L  \quad \Rightarrow \quad A[1+L*(M+S)+L*(i-1)+l,] $

$\gamma_{rl} \ge \beta \quad r=1,\dots, S,\; l=1,\ldots,L \quad \Rightarrow \quad A[1+2*L*M+l*S)+L*(r-1)+l,] $

$\beta>0 \quad \Rightarrow \quad A[2+2*L*(M+S),]$

In [8]:
# Constraints matrix A, by blocks:
A = array(0,c(NC,NV))

A[1,(N+L*M+1):(N+L*M+S*L)] = rep(1/(S*L),S*L)

for(i in 1:M){ A[(1+(i-1)*L+1):(1+(i-1)*L+L),1:N] = INPUTS[,i,]}

A[2:(1+M*L),(N+1):(N+L*M)] = diag(-c(INPUTS[,,dmu]))

for(r in 1:S){ A[(1+M*L+(r-1)*L+1):(1+M*L+(r-1)*L+L),1:N] = OUTPUTS[,r,]}

A[(1+M*L+1):(1+M*L+S*L),(N+L*M+1):(N+L*M+S*L)] = diag(-c(OUTPUTS[,,dmu]))

A[(2+L*(M+S)):(1+L*(2*M+S)),(N+1):(N+L*M)] = diag(1,M*L)

A[(2+L*(2*M+S)):(1+2*L*(M+S)),(N+L*M+1):(N+L*M+S*L)] = diag(1,S*L)

A[,N+L*(M+S)+1] = c(rep(0,1+L*(M+S)),rep(-1,L*(M+S)),1)


A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]  0    0    0    0    0     0    0    0    0   0     0     0     0   
 [2,] 12   14   20   20   20   -20    0    0    0   0     0     0     0   
 [3,] 12   14   20   20   20     0  -20    0    0   0     0     0     0   
 [4,] 12   14   20   20   20     0    0  -20    0   0     0     0     0   
 [5,] 12   14   20   20   20     0    0    0  -20   0     0     0     0   
 [6,]  8    7    8    6    5     0    0    0    0  -5     0     0     0   
 [7,]  8    7    8    6    6     0    0    0    0   0    -6     0     0   
 [8,]  8    7    8    6    6     0    0    0    0   0     0    -6     0   
 [9,]  8    7    8    6    7     0    0    0    0   0     0     0    -7   
[10,] 10   10   10   10   10     0    0    0    0   0     0     0     0   
[11,] 10   10   10   10   10     0    0    0    0   0     0     0     0   
[12,] 10   10   10   10   10     0    0    0    0   0     0     0     0   
[13,] 10   10   10   10   10     0    0    0    0   0     0     0     0   
[14,]  0    0    0    0    0     1    0    0    0   0     0     0     0   
[15,]  0    0    0    0    0     0    1    0    0   0     0     0     0   
[16,]  0    0    0    0    0     0    0    1    0   0     0     0     0   
[17,]  0    0    0    0    0     0    0    0    1   0     0     0     0   
[18,]  0    0    0    0    0     0    0    0    0   1     0     0     0   
[19,]  0    0    0    0    0     0    0    0    0   0     1     0     0   
[20,]  0    0    0    0    0     0    0    0    0   0     0     1     0   
[21,]  0    0    0    0    0     0    0    0    0   0     0     0     1   
[22,]  0    0    0    0    0     0    0    0    0   0     0     0     0   
[23,]  0    0    0    0    0     0    0    0    0   0     0     0     0   
[24,]  0    0    0    0    0     0    0    0    0   0     0     0     0   
[25,]  0    0    0    0    0     0    0    0    0   0     0     0     0   
[26,]  0    0    0    0    0     0    0    0    0   0     0     0     0   
      [,14]  [,15]  [,16]  [,17]  [,18]
 [1,]   0.25   0.25   0.25   0.25  0   
 [2,]   0.00   0.00   0.00   0.00  0   
 [3,]   0.00   0.00   0.00   0.00  0   
 [4,]   0.00   0.00   0.00   0.00  0   
 [5,]   0.00   0.00   0.00   0.00  0   
 [6,]   0.00   0.00   0.00   0.00  0   
 [7,]   0.00   0.00   0.00   0.00  0   
 [8,]   0.00   0.00   0.00   0.00  0   
 [9,]   0.00   0.00   0.00   0.00  0   
[10,] -10.00   0.00   0.00   0.00  0   
[11,]   0.00 -10.00   0.00   0.00  0   
[12,]   0.00   0.00 -10.00   0.00  0   
[13,]   0.00   0.00   0.00 -10.00  0   
[14,]   0.00   0.00   0.00   0.00 -1   
[15,]   0.00   0.00   0.00   0.00 -1   
[16,]   0.00   0.00   0.00   0.00 -1   
[17,]   0.00   0.00   0.00   0.00 -1   
[18,]   0.00   0.00   0.00   0.00 -1   
[19,]   0.00   0.00   0.00   0.00 -1   
[20,]   0.00   0.00   0.00   0.00 -1   
[21,]   0.00   0.00   0.00   0.00 -1   
[22,]   1.00   0.00   0.00   0.00 -1   
[23,]   0.00   1.00   0.00   0.00 -1   
[24,]   0.00   0.00   1.00   0.00 -1   
[25,]   0.00   0.00   0.00   1.00 -1   
[26,]   0.00   0.00   0.00   0.00  1

In [9]:
# Find the optimal solution
library("lpSolve")
#library("MASS")

optimum <-  lp(direction="min",
                 objective.in = C,
                 const.mat = A,
                 const.dir = constraints_direction,
                 const.rhs = B)

# LMFERM solution: 
sol.LMFERM <- optimum$solution
sol.LMFERM

round(sol.LMFERM,5)

[1] 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1

[1] 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1

In [10]:
# checking solutions
sum(sol.LMFERM[(N+L*M+1):(N+L*M+S*L)])/(S*L) # first constraint 
sol.LMFERM[N+L*(M+S)+1] #last element correspond with beta

[1] 1

[1] 1

**NOTE:** Do not forget the transformation of the variables, to get the FERM solutions

\begin{equation}
\begin{array}{l}
    {\displaystyle\frac{1}{\beta}}={\displaystyle{\frac{1}{2S(K+1)} \sum_{r=1}^{S} \sum_{k=0}^{K} (\gamma_{rk}^{L}+\gamma_{rk}^{R}) 
    \quad \rightarrow \quad 
    \displaystyle{\frac{1}{SL}} \sum_{r=1}^{S} \sum_{l=1}^{L} \gamma'_{rl} = 1
    }},\\
    \lambda'_j=\beta\lambda_j,\\
    \theta_{il}^{'L}=\beta\theta_{il}^{L},\quad
    \theta_{il}^{'R}=\beta\theta_{il}^{R}, \\
    \gamma_{rl}^{'L}=\beta\gamma_{rl}^{L}, \quad \gamma_{rl}^{'R}=\beta\gamma_{rl}^{R},\quad\forall j,i,r,l. 
    %j=1,\dots,n,\; i=1,\dots,m,\; r=1,\dots, s.
    \end{array}
\end{equation}

In [11]:
# MFERM solution (modified) FERM): 
beta[dmu] = sol.LMFERM[N+L*(M+S)+1]
lambda[dmu,] <- sol.LMFERM[1:N] / beta[dmu]
theta[dmu,] <- sol.LMFERM[(N+1):(N+M*L)]/beta[dmu]
gamma[dmu,] <- sol.LMFERM[(N+M*L+1):(N+L*(M+S))]/beta[dmu]

beta
lambda
theta
gamma

[1] 0 0 0 0 1

[,1] [,2] [,3] [,4] [,5]
[1,] 0    0    0    0    0   
[2,] 0    0    0    0    0   
[3,] 0    0    0    0    0   
[4,] 0    0    0    0    0   
[5,] 0    0    0    0    1

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 0    0    0    0    0    0    0    0   
[2,] 0    0    0    0    0    0    0    0   
[3,] 0    0    0    0    0    0    0    0   
[4,] 0    0    0    0    0    0    0    0   
[5,] 1    1    1    1    1    1    1    1

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0   
[4,] 0    0    0    0   
[5,] 1    1    1    1

In [12]:
# Showing the results for DMU 5: 
for(i in 1:M){
    print(paste("Input ",i))
    Z = theta[dmu,((i-1)*L+1):((i-1)*L+L)]
    for(l in 1:(L/2)){
        print(paste("Level ",l-1, ": thetaL=",round(Z[l],5) , "thetaR=",round(Z[L-l+1],5)))
    }
}


[1] "Input  1"
[1] "Level  0 : thetaL= 1 thetaR= 1"
[1] "Level  1 : thetaL= 1 thetaR= 1"
[1] "Input  2"
[1] "Level  0 : thetaL= 1 thetaR= 1"
[1] "Level  1 : thetaL= 1 thetaR= 1"


In [13]:
# Saving the objective value, or ERM, for (FERM) problem
ERM[dmu] = round(mean(theta[dmu,])/mean(gamma[dmu,]),3)

ERM

[1] 0 0 0 0 1

In [14]:
# Getting the targets: 
for(i in 1:M) Targets.X[,i,dmu] = round((INPUTS[,i,]) %*% lambda[dmu,],5)

for(r in 1:S) Targets.Y[,r,dmu] = round((OUTPUTS[,r,]) %*% lambda[dmu,],5)

Targets.X[,,dmu]
Targets.Y[,,dmu]

[,1] [,2]
[1,] 20   5   
[2,] 20   6   
[3,] 20   6   
[4,] 20   7

[1] 10 10 10 10

### NOW REPEAT THE WHOLE PROCESS FOR EACH DMU:

## Example 1 for Paper: 

In [18]:
# ARYA & YADAV (2017) : Hospitals
K = 1 # K=1-polygonal fuzzy number, RPFN_k
L = 3 # fuzzy length (triangular Fuzzy number)
N = 12 # DMU's
M = 2 # inputs
S = 2 # outputs 

#DATA: 
INPUTS <- array(c(10,13,15,3,5,8, 
                 10,12,14,3,5,7,
                 9,12,14,2,4,5,
                 6,8,11,1,1,3,
                 8,10,13,3,4,6,
                 10,11,12,2,3,4,
                 9,10,12,1,2,6,
                 9,11,15,1,4,7,
                 10,12,15,2,5,7,
                 10,16,20,2,4,6,
                 9,11,14,3,5,8, 
                 5,8,10,1,4,6), c(L,M,N)) 
#
OUTPUTS <- array(c(3640,3650,3655,134130,134137,134145, 
                   4150,4160,4170,116055,116062,116068, 
                   4360,4370,4380,94060,94066,94072, 
                   485,492,500,24320,24329,24335, 
                   2460,2464,2470,99740,99748,99760,
                   1360,1368,1375,49395,49401,49410,
                   1055,1062,1070,37765,37772,37780,
                   1295,1302,1310,82835,82841,82850,
                   1660,1671,1680,100590,100596,100605,
                   1010,1018,1025,64345,64351,64360,
                   1500,1504,1510,80050,80056,80061,
                   1960,1965,1972,58160,58167,58175),c(L,S,N)) 



# Define variable arrays, for each DMU (N):
ERM = array(0,N)
beta = array(0,N)
lambda = array(0,c(N,N))
theta = array(0,c(N,M*L))
gamma = array(0,c(N,S*L))

Targets.X = array(0,c(L,M,N))
Targets.Y = array(0,c(L,S,N))

NV = N+(M+S)*L+1 # variables, and
NC = 2*L*(M+S)+2 # constraints

# Getting the MATRIX NOTATION for solving with lp function: 
# min Cx s.t Ax <= B

## Set the coefficients of the decision variables -> C
C <- c(rep(0,N),rep(1/(M*L),M*L),rep(0,S*L+1))
    
# Right hand side for the constraints
B <- c(1,rep(0,NC-1))

##
constraints_direction  <- c("=",rep("<=",M*L), rep(">=",S*L), 
                               rep("<=",M*L), rep(">=",S*L),">")

# C,B and constraints_direction are outside the loop,  
# since they are the same for each DMU

for(dmu in 1:N){
    # Constraints matrix A, the only element which change for each DMU
    A = array(0,c(NC,NV))

    A[1,(N+L*M+1):(N+L*M+S*L)] = rep(1/(S*L),S*L)
    
    for(i in 1:M){ A[(1+(i-1)*L+1):(1+(i-1)*L+L),1:N] = INPUTS[,i,]}
    #
    A[2:(1+M*L),(N+1):(N+L*M)] = diag(-c(INPUTS[,,dmu]))
    
    for(r in 1:S){ A[(1+M*L+(r-1)*L+1):(1+M*L+(r-1)*L+L),1:N] = OUTPUTS[,r,]}
    
    A[(1+M*L+1):(1+M*L+S*L),(N+L*M+1):(N+L*M+S*L)] = diag(-c(OUTPUTS[,,dmu]))
    A[(2+L*(M+S)):(1+L*(2*M+S)),(N+1):(N+L*M)] = diag(1,M*L)
    A[(2+L*(2*M+S)):(1+2*L*(M+S)),(N+L*M+1):(N+L*M+S*L)] = diag(1,S*L)
    A[,N+L*(M+S)+1] = c(rep(0,1+L*(M+S)),rep(-1,L*(M+S)),1)

    optimum <-  lp(direction="min",
                 objective.in = C,
                 const.mat = A,
                 const.dir = constraints_direction,
                 const.rhs = B)

    # LMFERM solution: 
    sol.LMFERM <- optimum$solution
    beta[dmu] = sol.LMFERM[N+L*(M+S)+1]
    lambda[dmu,] <- sol.LMFERM[1:N] 
    theta[dmu,] <- sol.LMFERM[(N+1):(N+M*L)]
    gamma[dmu,] <- sol.LMFERM[(N+M*L+1):(N+L*(M+S))]
    
    # MFERM solution (modified) FERM): undo the transformation of variables
    #beta[dmu] = sol.LMFERM[N+L*(M+S)+1]
    #lambda[dmu,] <- sol.LMFERM[1:N] / beta[dmu]
    #theta[dmu,] <- sol.LMFERM[(N+1):(N+M*L)]/beta[dmu]
    #gamma[dmu,] <- sol.LMFERM[(N+M*L+1):(N+L*(M+S))]/beta[dmu]
    
    # Saving the objective value, or ERM, for (FERM) problem
    ERM[dmu] = round(mean(theta[dmu,])/mean(gamma[dmu,]),3)
    print(paste("DMU:",dmu,"R^F:",ERM[dmu]))
    
    # Getting the targets: 
    for(i in 1:M) Targets.X[,i,dmu] = round((INPUTS[,i,]) %*% lambda[dmu,],5)

    for(r in 1:S) Targets.Y[,r,dmu] = round((OUTPUTS[,r,]) %*% lambda[dmu,],5)
    
}

[1] "DMU: 1 R^F: 1"
[1] "DMU: 2 R^F: 1"
[1] "DMU: 3 R^F: 1"
[1] "DMU: 4 R^F: 0.33"
[1] "DMU: 5 R^F: 0.834"
[1] "DMU: 6 R^F: 0.441"
[1] "DMU: 7 R^F: 0.414"
[1] "DMU: 8 R^F: 1"
[1] "DMU: 9 R^F: 0.602"
[1] "DMU: 10 R^F: 0.3"
[1] "DMU: 11 R^F: 0.423"
[1] "DMU: 12 R^F: 1"


In [19]:
theta

[,1]      [,2]      [,3]      [,4]      [,5]      [,6]     
 [1,] 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
 [2,] 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
 [3,] 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
 [4,] 0.2401304 0.2387766 0.2021060 0.3454458 0.6583992 0.2932869
 [5,] 0.8801290 0.8801290 0.7854831 0.7020215 0.8790138 0.8764117
 [6,] 0.3529859 0.4278617 0.4575744 0.3922066 0.5229421 0.4902582
 [7,] 0.3028458 0.3634150 0.3533201 0.6056917 0.6056917 0.2523715
 [8,] 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
 [9,] 0.5947586 0.6446242 0.6211117 0.6446242 0.5448930 0.5647089
[10,] 0.3127179 0.2605983 0.2432250 0.3474644 0.3474644 0.2895536
[11,] 0.4902787 0.5348495 0.4902787 0.3268525 0.3922230 0.3064242
[12,] 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000

In [20]:
gamma

[,1]     [,2]     [,3]     [,4]      [,5]      [,6]     
 [1,] 1.000000 1.000000 1.000000 1.0000000 1.0000000 1.0000000
 [2,] 1.000000 1.000000 1.000000 1.0000000 1.0000000 1.0000000
 [3,] 1.000000 1.000000 1.000000 1.0000000 1.0000000 1.0000000
 [4,] 1.358441 1.342294 1.323622 0.6587240 0.6585203 0.6583992
 [5,] 1.119316 1.120360 1.119802 0.8802068 0.8801856 0.8801290
 [6,] 1.257368 1.252882 1.249356 0.7468560 0.7468129 0.7467245
 [7,] 1.251571 1.246174 1.239687 0.7542878 0.7541961 0.7540845
 [8,] 1.000000 1.000000 1.000000 1.0000000 1.0000000 1.0000000
 [9,] 1.360284 1.354925 1.350896 0.6446347 0.6446362 0.6446242
[10,] 1.499945 1.491571 1.484775 0.5079260 0.5079110 0.5078724
[11,] 1.425077 1.424547 1.422133 0.5760852 0.5760788 0.5760795
[12,] 1.000000 1.000000 1.000000 1.0000000 1.0000000 1.0000000

In [22]:
dmu=5
Targets.X[,,dmu]

[,1]     [,2]   
[1,]  7.04103 2.10606
[2,]  8.80129 3.51606
[3,] 10.21128 5.25847

In [23]:
dmu=5
Targets.Y[,,dmu]

[,1]     [,2]    
[1,] 2753.518 87791.83
[2,] 2760.568 87796.75
[3,] 2765.911 87801.67

## Repeat the process for Example 2, K=2-polygonal Fuzzy Numbers

### DATA:

**DMU Input1(5 components) Input2 Output1 Output2** 

1 10  10.81  13  13.04  15    3  3.12  5  5.48  8    3640  3640.21  3650  3650.43  3655   134130  134135.68  134137  134142.45  134145 

2  10  11.7  12  13.09  14    3  4.67  5  6.12  7    4150  4151.64  4160  4165.69  4170   116055  116061.78  116062  116062.42  116068  

3  9  10.09  12  13.68  14    2  3.69  4  4.48  5    4360  4365.12  4370  4378.88  4380   94060  94060.14  94066  94066.43  94072  

4    6  6.69  8  10.45  11    1  1  1  1.63  3    485  486.62  492  496.94  500   24320  24320.38  24329  24330.7  24335  

5   8  8.5  10  10.13  13    3  3.82  4  4.18  6    2460  2463.42  2464  2468.91  2470   99740  99743.96  99748  99754.3  99760  

6    10  10.05  11  11.62  12    2  2.38  3  3.71  4    1360  1364.87  1368  1370.22  1375   49395  49396.58  49401  49407.19  49410  

7    9  10  10  10  12    1  2  2  2  6   1055  1062  1062  1062  1070   37765  37772  37772  37772  37780  

8     9  11  11  11  15    1  4  4  4  7  1295  1302  1302  1302  1310   82835  82841  82841  82841  82850  

9    10  12  12  12  15    2  5  5  5  7  1660  1671  1671  1671  1680   100590  100596  100596  100596  100605  

10    10  16  16  16  20    2  4  4  4  6  1010  1018  1018  1018  1025   64345  64351  64351  64351  64360 

11    9  11  11  11  14    3  5  5  5  8   1500  1504  1504  1504  1510    80050  80056  80056  80056  80061 

12     5  8  8  8  10    1  4  4  4  6    1960  1965  1965  1965  1972     58160  58167  58167  58167  58175  



In [24]:
K = 2 # K=1-polygonal fuzzy number, RPFN_k
L = 5 # fuzzy length (pentagonal Fuzzy number)
N = 12 # DMU's
M = 2 # inputs
S = 2 # outputs 

#DATA: 
INPUTS <- array(c(10,  10.81,  13,  13.04,  15, 3 , 3.12,  5 , 5.48,  8,
                 ...
                 5,  8,  8,  8,  10,   1,  4,  4,  4 , 6), c(L,M,N)) 
#

ERROR: Error in parse(text = x, srcfile = src): <text>:10:18: unexpected numeric constant
9:                  ...
10:                  5
                     ^
